experiment_id: auto
dataset: endoscopy
model_type: eomt
vit_name: "facebook/dinov3-vits16-pretrain-lvd1689m" 
decoder: linear
image_size: [448, 448]
n_folds: 5


# optimization
lr: 0.0001
llrd: 0.90
lr_multi: 1.5
poly_power: 0.95
weight_decay: 0.05
epochs: 200
early_stop_patience: 30
batch_size: 4
num_workers: 9
freeze_encoder: False
unfreeze_last_k: 0


non_vit_warmup: 1
vit_warmup: 2

# training setup
train_tf_kind: aug
val_tf_kind: basic

# optional
seed: 42
few_shot_pct: 0.05

vit_ckpt: null

# eomt specific
eomt_num_q: 6
eomt_num_blocks: 4
eomt_masked_attn_enabled: True

# --- mask2former loss weights / sampling ---
num_points: 12544
oversample_ratio: 3.0
importance_sample_ratio: 0.75
no_object_coefficient: 0.1
mask_coefficient: 5.0 
dice_coefficient: 5.0  
class_coefficient: 2.0
